### ISSUE TITLE
[openvsp] vspsurf compile error

### ISSUE THREAD

**Issue by vldw** [acxz/pkgbuilds#203]
I have tried installing openvsp again with `yay -Syu openvsp` and deleted the flags mentioned in the previous thread namely the `-Werror=format-security` flag  from `/etc/makepkg.conf`and it will still not compile.

[openvsp.log](https://github.com/acxz/pkgbuilds/files/9032947/openvsp.log)
here is the log where it failed to compile:
```[ 54%] Linking CXX executable vspaero
[ 54%] Built target vspaero
make[2]: *** [util/CMakeFiles/util.dir/build.make:398: util/CMakeFiles/util.dir/VspSurf.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:837: util/CMakeFiles/util.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: openvsp

**Comment by acxz** [comment]
The log file you have submitted is not complete. Please run the following command to obtain the full log:
`yay -Syu openvsp |& tee openvsp.log`.

I assume you have closed this issue as you have figured out the solution?

**Comment by acxz** [comment]
To clarify the error:
```
/home/acxz/vcs/git/github/acxz/pkgbuilds/openvsp-git/src/OpenVSP/src/util/VspSurf.cpp: In member function ‘bool VspSurf::CapUMin(int, double, double, double, bool)’:
/home/acxz/vcs/git/github/acxz/pkgbuilds/openvsp-git/src/OpenVSP/src/util/VspSurf.cpp:1892:33: error: no matching function for call to ‘eli::geom::surface::piecewise_multicap_surface_creator<double, 3, eli::util::tolerance<double> >::set_conditions(piecewise_surface_type&, int&, double, eli::geom::surface::piecewise_multicap_surface_creator<double, 3, eli::util::tolerance<double> >::edge_cap_identifier, double&, double&, double&, bool&)’
 1892 |     rtn_flag = cc.set_conditions(m_Surface, captype, 1.0, multicap_creator_type::CAP_UMIN, len, offset, str, swflag );
      |                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/acxz/vcs/git/github/acxz/pkgbuilds/openvsp-git/src/OpenVSP/src/util/VspSurf.cpp:24:
/usr/include/eli/geom/surface/piecewise_multicap_surface_creator.hpp:85:16: note: candidate: ‘bool eli::geom::surface::piecewise_multicap_surface_creator<data__, dim__, tol__>::set_conditions(const piecewise_surface_type&, const index_type&, const data_type&, edge_cap_identifier, const data_type&, const data_type&, const data_type&, const point_type&, const bool&) [with data__ = double; short unsigned int dim__ = 3; tol__ = eli::util::tolerance<double>; piecewise_surface_type = eli::geom::surface::piecewise<eli::geom::surface::bezier, double, 3>; index_type = long int; data_type = double; point_type = Eigen::Matrix<double, 1, 3>]’
   85 |           bool set_conditions(const piecewise_surface_type &os, const index_type & typ, const data_type &dp, edge_cap_identifier ec, const data_type &lf, const data_type &of, const data_type &sf, const point_type & pnt, const bool &sc )
      |                ^~~~~~~~~~~~~~
/usr/include/eli/geom/surface/piecewise_multicap_surface_creator.hpp:85:16: note:   candidate expects 9 arguments, 8 provided
/home/acxz/vcs/git/github/acxz/pkgbuilds/openvsp-git/src/OpenVSP/src/util/VspSurf.cpp: In member function ‘bool VspSurf::CapUMax(int, double, double, double, bool)’:
/home/acxz/vcs/git/github/acxz/pkgbuilds/openvsp-git/src/OpenVSP/src/util/VspSurf.cpp:1940:33: error: no matching function for call to ‘eli::geom::surface::piecewise_multicap_surface_creator<double, 3, eli::util::tolerance<double> >::set_conditions(piecewise_surface_type&, int&, double, eli::geom::surface::piecewise_multicap_surface_creator<double, 3, eli::util::tolerance<double> >::edge_cap_identifier, double&, double&, double&, bool&)’
 1940 |     rtn_flag = cc.set_conditions(m_Surface, captype, 1.0, multicap_creator_type::CAP_UMAX, len, offset, str, swflag );
      |                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/eli/geom/surface/piecewise_multicap_surface_creator.hpp:85:16: note: candidate: ‘bool eli::geom::surface::piecewise_multicap_surface_creator<data__, dim__, tol__>::set_conditions(const piecewise_surface_type&, const index_type&, const data_type&, edge_cap_identifier, const data_type&, const data_type&, const data_type&, const point_type&, const bool&) [with data__ = double; short unsigned int dim__ = 3; tol__ = eli::util::tolerance<double>; piecewise_surface_type = eli::geom::surface::piecewise<eli::geom::surface::bezier, double, 3>; index_type = long int; data_type = double; point_type = Eigen::Matrix<double, 1, 3>]’
   85 |           bool set_conditions(const piecewise_surface_type &os, const index_type & typ, const data_type &dp, edge_cap_identifier ec, const data_type &lf, const data_type &of, const data_type &sf, const point_type & pnt, const bool &sc )
      |                ^~~~~~~~~~~~~~
/usr/include/eli/geom/surface/piecewise_multicap_surface_creator.hpp:85:16: note:   candidate expects 9 arguments, 8 provided
make[5]: *** [src/util/CMakeFiles/util.dir/build.make:398: src/util/CMakeFiles/util.dir/VspSurf.cpp.o] Error 1
```

**Comment by acxz** [comment]
Should be resolved with: [c8e995f](https://github.com/acxz/pkgbuilds/commit/c8e995f4f4549e50819127e417e10029e4591902)

**Comment by vldw** [comment]
I am still having issues building the package.
Currently I am experiencing error in building the geom_core
Here is the log:
[openvsp.log](https://github.com/acxz/pkgbuilds/files/9060678/openvsp.log)

**Comment by acxz** [comment]
Error from log:
```
[ 66%] Building CXX object geom_core/CMakeFiles/geom_core.dir/LinkMgr.cpp.o
malloc(): memory corruption (fast)
malloc(): unaligned fastbin chunk detected 2
[ 67%] Building CXX object geom_core/CMakeFiles/geom_core.dir/MaterialMgr.cpp.o
c++: internal compiler error: Aborted signal terminated program cc1plus
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://bugs.archlinux.org/> for instructions.
```

Cannot reproduce.

This looks like an out of memory issue. Can you try again, but while monitoring your memory usage (i.e. have htop and any other process monitoring tool open) to see if you are reaching the limits of you RAM? How much RAM and CPU cores do you have?

The solution to this would be trying to compile openvsp with a smaller number of cores. You can edit this in the `/etc/makepkg.conf` file under the `MAKEFLAGS` flag. Decreasing the number of cores, will decrease the amount of RAM is needed during the compilation and should let openvsp to compile successfully.

**Comment by vldw** [comment]
I have 4 cores and 8 GB of RAM. I recently tried to build the package and it compiled. Not sure what was wrong with that day. Thanks for the help!

**Comment by acxz** [comment]
> Not sure what was wrong with that day. 

Maybe you had some background processes running that was limiting the amount of memory the compilation required?

In any case, I'm glad you got it to work!
